### ISSUE TITLE
Make images clickable and have them open the business’ website in a new tab

### ISSUE THREAD

**Issue by jvsinghk** [jvsinghk/ravenous#6]

**Comment by adgai19** [comment]
Can I work on this too?

**Comment by jvsinghk** [comment]
Please share your approach to resolve this issue?

**Comment by adgai19** [comment]
> Please share your approach to resolve this issue?

Sure. 
the response from the query to yelp has a field named url. I will be adding as a field to the state in the business property in the state. And I'll wrap the image in an anchor tag and set the href field  as the url that has been passed from the business property from the state.

**Comment by adgai19** [comment]
I am assuming that is the url that you want to open. If you want any other url to open than please do tell.

**Comment by jvsinghk** [comment]
Hey, @adgai19 The response of the yelp has a field named URL. which will redirect to the yelp site of that particular business when clicked on the image. I am thinking of redirecting it to the main business site if that exists if not than the yelp site of that business. Most of them actually have a business site link. Which we can retrieve and use. What do you think?

**Comment by jvsinghk** [comment]
@adgai19 For now, You can go ahead 😀 with redirecting it to yelp provided URL in the response to redirect it to the yelp site of that business. We will look into it later. Looking forward to your PR 🚀🚀

**Comment by adgai19** [comment]
![Hnet-image(3)](https://user-images.githubusercontent.com/29275245/95089536-e15a6b00-0741-11eb-821c-b989518c59e3.gif)
@jvsinghk here's a small demo of the current status.
